ORG_NAME: 'Brighton & Hove'
ADMIN_PREFIX: '/admin'
ADMIN_PASSWORD: 'xxxxxxxx'
ASSET_HOST: null

ALAVETELI_FEED_URL: 'http://www.whatdotheyknow.com/api/v2/body/nn/request_events.json'
ALAVETELI_API_KEY: 'xxxx'

# The base of the API endpoint to use for pushing new requests to.
ALAVETELI_API_ENDPOINT: 

# To perform an integration tests relating to pushing requests, start
# an Alaveteli server at this location for the tests to pass.  Leave
# this value blank to skip such tests.
TEST_ALAVETELI_API_HOST: http://localhost:3001

PULL_FROM_ALAVETELI: false
ALAVETELI_INITIAL_LAST_EVENT_ID: null
