#!/bin/bash

# Symlink ruby 1.9.1 into our vhost folder and setup our $PATH so that we use
# it as ruby, necessary to make bundler et all install the right gems
if [ ! -e ../bin/ruby ]; then
    echo "Symlinking ruby1.9.1 as ../bin/ruby"
    mkdir -p ../bin
    ln -sf /usr/bin/ruby1.9.1 ../bin/ruby
fi
BIN_DIR="`(cd ../bin && pwd)`"
export PATH="$BIN_DIR:$PATH"
echo "Ruby version is now: `../bin/ruby -v`"

if [ -e config/httpd.conf ] && egrep -q '^\s*RackEnv\s*production' config/httpd.conf
then
    export RAILS_ENV=production
else
    export RAILS_ENV=development
fi

bundle install --deployment
bundle exec rake db:migrate
bundle exec rake bootstrap:add

if [ "$RAILS_ENV" = production ]
then
    bundle exec rake assets:precompile
fi
